package GUI;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JMainFrame.java
 *
 * Created on Jul 1, 2010, 9:14:56 AM
 */

/**
 *
 * @author KOKICHI
 */
public class JMainFrame extends javax.swing.JFrame {

    /** Creates new form JMainFrame */
    public JMainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsername = new javax.swing.JLabel();
        lbSignout = new javax.swing.JLabel();
        lbCalendar = new javax.swing.JLabel();
        lbChangePassword = new javax.swing.JLabel();
        lbHelp = new javax.swing.JLabel();
        lbViewReport = new javax.swing.JLabel();
        lbTotalLeaveDay = new javax.swing.JLabel();
        lbRemainingLeaveDay = new javax.swing.JLabel();
        lbYear = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLeave = new javax.swing.JTable();
        btApplyLeave = new javax.swing.JButton();
        btWithdraw = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leave Management System");

        lbUsername.setText("Login as");
        lbUsername.setName("lbUsername"); // NOI18N

        lbSignout.setText("Sign out");
        lbSignout.setName("lbSignout"); // NOI18N

        lbCalendar.setText("Calendar");
        lbCalendar.setName("lbCalendar"); // NOI18N

        lbChangePassword.setText("Change Password");
        lbChangePassword.setName("lbChangePassword"); // NOI18N

        lbHelp.setText("Help");
        lbHelp.setName("lbHelp"); // NOI18N

        lbViewReport.setText("View report");
        lbViewReport.setName("lbViewReport"); // NOI18N

        lbTotalLeaveDay.setText("Total leave day");
        lbTotalLeaveDay.setName("lbTotalLeaveDay"); // NOI18N

        lbRemainingLeaveDay.setText("Remaining leave day");
        lbRemainingLeaveDay.setName("lbRemainingLeaveDay"); // NOI18N

        lbYear.setText("Year");
        lbYear.setName("lbYear"); // NOI18N

        cbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2009", "2008" }));
        cbYear.setName("cbYear"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tbLeave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLeave.setName("tbLeave"); // NOI18N
        jScrollPane1.setViewportView(tbLeave);

        btApplyLeave.setText("Apply leave");
        btApplyLeave.setName("btApplyLeave"); // NOI18N

        btWithdraw.setText("Withdraw");
        btWithdraw.setName("btWithdraw"); // NOI18N

        btCancel.setText("Cancel");
        btCancel.setName("btCancel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbUsername)
                                .addGap(46, 46, 46)
                                .addComponent(lbSignout)
                                .addGap(58, 58, 58)
                                .addComponent(lbCalendar))
                            .addComponent(lbTotalLeaveDay))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbYear)
                                .addGap(18, 18, 18)
                                .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbChangePassword)
                                .addGap(71, 71, 71)
                                .addComponent(lbViewReport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(lbHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRemainingLeaveDay)
                        .addContainerGap(522, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btApplyLeave)
                .addGap(18, 18, 18)
                .addComponent(btWithdraw)
                .addGap(18, 18, 18)
                .addComponent(btCancel)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsername)
                    .addComponent(lbSignout)
                    .addComponent(lbCalendar)
                    .addComponent(lbChangePassword)
                    .addComponent(lbHelp)
                    .addComponent(lbViewReport))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalLeaveDay)
                    .addComponent(lbYear)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRemainingLeaveDay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btApplyLeave)
                    .addComponent(btWithdraw)
                    .addComponent(btCancel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApplyLeave;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btWithdraw;
    private javax.swing.JComboBox cbYear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCalendar;
    private javax.swing.JLabel lbChangePassword;
    private javax.swing.JLabel lbHelp;
    private javax.swing.JLabel lbRemainingLeaveDay;
    private javax.swing.JLabel lbSignout;
    private javax.swing.JLabel lbTotalLeaveDay;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lbViewReport;
    private javax.swing.JLabel lbYear;
    private javax.swing.JTable tbLeave;
    // End of variables declaration//GEN-END:variables

}
